apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.10/manifests/install.yaml
  - argocd-notifications-secret.yaml
patchesStrategicMerge:
  - argocd-notifications-secret-patch.yaml
  - argocd-notifications-cm-patch.yaml